import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { submitSmtpMessage } from "../src/index.ts";
import { FakeSmtpServer, type FakeSmtpServerOptions } from "./fake-smtp-server.ts";
import { createTestAuthority, type TestAuthority, type TestCertificate } from "./test-certificates.ts";

/**
 * Message submission over the fake SMTP server (SPEC F7 step 3 and
 * section 12). Every accepted case proves the strongest property directly:
 * the server received exactly the pregenerated bytes, on a verified
 * connection, under the explicit envelope. The scripted refusals prove the
 * outcome classification the send service depends on.
 */

const HOST = "localhost";
const USER = "user@example.com";
const PASSWORD = "mailbox-secret";

/** Fast timeouts keep the failure cases from stalling the suite. */
const TIMEOUTS = { connectMs: 4_000, greetingMs: 4_000, socketMs: 8_000 };

const ENVELOPE = {
  from: "user@example.com",
  to: ["to@example.com", "cc@example.com", "bcc@example.com"],
};

/**
 * One complete pregenerated message, as a snapshot would store it. The body
 * ends on its last line: the terminating `<CRLF>.<CRLF>` owns the final
 * `CRLF`, so the server reconstructs exactly these bytes.
 */
const RAW = Buffer.from(
  [
    "From: Main User <user@example.com>",
    "To: to@example.com",
    "Cc: cc@example.com",
    "Subject: Exact bytes",
    "Date: Mon, 07 Sep 2026 10:00:00 +0000",
    "Message-ID: <fixed-message-id@example.com>",
    "MIME-Version: 1.0",
    "",
    "The body the server must receive unchanged.",
  ].join("\r\n"),
  "utf8",
);

let authority: TestAuthority;
let valid: TestCertificate;
let selfSigned: TestCertificate;

const servers: FakeSmtpServer[] = [];

/** Start one fake submission server this suite stops afterwards. */
async function startSmtp(options: Partial<FakeSmtpServerOptions>): Promise<FakeSmtpServer> {
  const server = await FakeSmtpServer.start({
    mode: "starttls",
    certificate: valid,
    auth: { user: USER, pass: PASSWORD },
    submission: {},
    ...options,
  });
  servers.push(server);
  return server;
}

/** The request every test sends: exact bytes, explicit envelope, trust. */
function request(port: number, trustedCaPem?: string[]) {
  return {
    host: HOST,
    port,
    security: "starttls_required" as const,
    username: USER,
    password: PASSWORD,
    envelope: ENVELOPE,
    raw: new Uint8Array(RAW),
    timeouts: TIMEOUTS,
    ...(trustedCaPem === undefined ? {} : { trustedCaPem }),
  };
}

beforeAll(async () => {
  authority = createTestAuthority();
  valid = authority.issue({ hosts: [HOST], ips: ["127.0.0.1"] });
  selfSigned = authority.selfSigned({ hosts: [HOST] });
});

afterAll(async () => {
  await Promise.all(servers.map((server) => server.stop()));
});

describe("SMTP message submission", () => {
  it("delivers the exact bytes under the explicit envelope", async () => {
    const server = await startSmtp({});
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("accepted");
    expect(report.response).toBe("250 2.0.0 Ok: queued");
    expect(report.responseCode).toBe(250);
    expect(report.recipients).toEqual([
      { address: "to@example.com", accepted: true, response: "250 2.0.0 Ok: queued" },
      { address: "cc@example.com", accepted: true, response: "250 2.0.0 Ok: queued" },
      { address: "bcc@example.com", accepted: true, response: "250 2.0.0 Ok: queued" },
    ]);
    expect(report.error).toBeNull();
    expect(server.mailFrom).toBe(ENVELOPE.from);
    expect(server.acceptedRecipients).toEqual(ENVELOPE.to);
    expect(Buffer.compare(server.receivedMessage(), RAW)).toBe(0);
    expect(server.sawAuthenticationOverTls()).toBe(true);
  });

  it("submits over implicit TLS", async () => {
    const server = await startSmtp({ mode: "implicit" });
    const report = await submitSmtpMessage({
      ...request(server.port, [authority.certPem]),
      security: "implicit_tls",
    });

    expect(report.state).toBe("accepted");
    expect(server.receivedMessage().equals(RAW)).toBe(true);
  });

  it("reports one refused recipient beside the accepted ones", async () => {
    const server = await startSmtp({ submission: { rejectedRecipients: ["bcc@example.com"] } });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("accepted");
    const refused = report.recipients.find((entry) => entry.address === "bcc@example.com");
    expect(refused?.accepted).toBe(false);
    expect(refused?.response).toContain("550");
    expect(report.recipients.filter((entry) => entry.accepted)).toHaveLength(2);
  });

  it("classifies a refused final response as rejected", async () => {
    const server = await startSmtp({ submission: { finalResponse: "550 5.7.1 Message refused" } });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("rejected");
    expect(report.response).toBe("550 5.7.1 Message refused");
    expect(report.responseCode).toBe(550);
  });

  it("classifies a refused sender as rejected", async () => {
    const server = await startSmtp({ submission: { rejectSender: true } });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EENVELOPE");
    expect(server.receivedMessage().length).toBe(0);
  });

  it("classifies a refusal of every recipient as rejected", async () => {
    const server = await startSmtp({ submission: { rejectedRecipients: ENVELOPE.to } });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EENVELOPE");
    expect(report.recipients.every((entry) => !entry.accepted)).toBe(true);
  });

  it("classifies refused credentials as rejected", async () => {
    const server = await startSmtp({ auth: null });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EAUTH");
    expect(server.sawMailSubmission()).toBe(false);
  });

  it("refuses to submit unauthenticated when the server advertises no AUTH", async () => {
    const server = await startSmtp({ advertiseAuth: false });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    // Without `forceAuth` nodemailer would skip the login and hand the
    // message to the server anyway, unauthenticated (SPEC section 9).
    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EAUTH");
    expect(server.sawMailSubmission()).toBe(false);
    expect(server.acceptedRecipients).toEqual([]);
  });

  it("classifies a refused STARTTLS upgrade as rejected", async () => {
    const server = await startSmtp({ mode: "starttls-missing" });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("ETLS");
    expect(server.sawMailSubmission()).toBe(false);
  });

  it("leaves an untrusted certificate unclassified, before any mail", async () => {
    const server = await startSmtp({ certificate: selfSigned });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    // Certificate failures surface as `ESOCKET`, the same code a mid-session
    // drop uses, so the report cannot claim nothing was sent.
    expect(report.state).toBe("unknown");
    expect(server.sawMailSubmission()).toBe(false);
  });

  it("classifies a dropped final response as unknown", async () => {
    const server = await startSmtp({ submission: { dropAfterData: true } });
    const report = await submitSmtpMessage(request(server.port, [authority.certPem]));

    expect(report.state).toBe("unknown");
  });
});
