import net from "node:net";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { submitSmtpMessage } from "@mail-hub/transport";
import {
  createTestAuthority,
  ScriptedSmtpServer,
  type ScriptedSmtpServerOptions,
  type SmtpSubmissionScript,
  type TestAuthority,
  type TestCertificate,
} from "../src/index.ts";

/**
 * The scripted SMTP server against the production submitter (SPEC F7 and
 * section 12).
 *
 * `submitSmtpMessage` runs here exactly as the send service calls it: verified
 * TLS, explicit envelope, exact pregenerated bytes. The scripts bend one stage
 * of one conversation — refused senders, refused and deferred recipients, a
 * refused DATA, refused or lost final responses, a cut-off transfer, a stalled
 * answer, and a session refused before the greeting — so each test proves the
 * outcome classification and the duplicate-safety counters the acceptance
 * suites read.
 */

const HOST = "localhost";
const USER = "user@example.com";
const PASSWORD = "mailbox-secret";

/** Fast timeouts keep the failure cases from stalling the suite. */
const TIMEOUTS = { connectMs: 4_000, greetingMs: 4_000, socketMs: 8_000 };

const ENVELOPE = {
  from: "user@example.com",
  to: ["to@example.com", "cc@example.com", "bcc@example.com"],
};

/**
 * One complete pregenerated message, as a snapshot would store it. One body
 * line begins with a dot, so the accepted case also proves the server undoes
 * SMTP dot-stuffing before comparing bytes.
 */
const RAW = Buffer.from(
  [
    "From: Main User <user@example.com>",
    "To: to@example.com",
    "Cc: cc@example.com",
    "Subject: Exact bytes",
    "Date: Mon, 07 Sep 2026 10:00:00 +0000",
    "Message-ID: <fixed-message-id@example.com>",
    "MIME-Version: 1.0",
    "",
    "The body the server must receive unchanged.",
    ".dot-leading line the wire doubles",
    "Last line.",
  ].join("\r\n"),
  "utf8",
);

let authority: TestAuthority;
let certificate: TestCertificate;
const servers: ScriptedSmtpServer[] = [];

/** Start one scripted server this suite stops afterwards. */
async function startSmtp(
  options: Partial<ScriptedSmtpServerOptions> & { submission?: SmtpSubmissionScript },
): Promise<ScriptedSmtpServer> {
  const server = await ScriptedSmtpServer.start({
    mode: "starttls",
    certificate,
    auth: { user: USER, pass: PASSWORD },
    submission: {},
    ...options,
  });
  servers.push(server);
  return server;
}

/** One submission request: exact bytes, explicit envelope, trusted anchor. */
function request(port: number, timeouts = TIMEOUTS) {
  return {
    host: HOST,
    port,
    security: "starttls_required" as const,
    username: USER,
    password: PASSWORD,
    envelope: ENVELOPE,
    raw: new Uint8Array(RAW),
    timeouts,
    trustedCaPem: [authority.certPem],
  };
}

beforeAll(() => {
  authority = createTestAuthority();
  certificate = authority.issue({ hosts: [HOST], ips: ["127.0.0.1"] });
});

afterAll(async () => {
  await Promise.all(servers.map((server) => server.stop()));
});

describe("scripted SMTP server", () => {
  it("receives the exact bytes under the explicit envelope", async () => {
    const server = await startSmtp({});
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("accepted");
    expect(report.response).toBe("250 2.0.0 Ok: queued");
    expect(report.recipients.map((entry) => entry.accepted)).toEqual([true, true, true]);
    const completed = server.completedSubmissions();
    expect(completed).toHaveLength(1);
    expect(completed[0]!.mailFrom).toBe(ENVELOPE.from);
    expect(completed[0]!.acceptedRecipients).toEqual(ENVELOPE.to);
    // Dot-stuffing undone: the stored bytes equal the pregenerated snapshot.
    expect(Buffer.compare(completed[0]!.message!, RAW)).toBe(0);
  });

  it("submits over implicit TLS", async () => {
    const server = await startSmtp({ mode: "implicit" });
    const report = await submitSmtpMessage({
      ...request(server.port),
      security: "implicit_tls",
    });

    expect(report.state).toBe("accepted");
    expect(Buffer.compare(server.completedSubmissions()[0]!.message!, RAW)).toBe(0);
  });

  it("keeps a deferred recipient beside the accepted ones", async () => {
    const server = await startSmtp({ submission: { deferredRecipients: ["cc@example.com"] } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("accepted");
    const deferred = report.recipients.find((entry) => entry.address === "cc@example.com");
    expect(deferred?.accepted).toBe(false);
    expect(deferred?.response).toContain("451");
    expect(report.recipients.filter((entry) => entry.accepted)).toHaveLength(2);
    const attempt = server.submissions[0]!;
    expect(attempt.rejectedRecipients[0]!.response).toContain("451");
  });

  it("counts a refused sender as rejected, with nothing stored", async () => {
    const server = await startSmtp({ submission: { rejectSender: true } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EENVELOPE");
    expect(server.completedSubmissions()).toHaveLength(0);
  });

  it("counts a refusal of every recipient as rejected", async () => {
    const server = await startSmtp({ submission: { rejectedRecipients: ENVELOPE.to } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EENVELOPE");
    expect(report.recipients.every((entry) => !entry.accepted)).toBe(true);
    expect(server.completedSubmissions()).toHaveLength(0);
  });

  it("counts a refused DATA command as rejected", async () => {
    const server = await startSmtp({ submission: { rejectDataCommand: true } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EENVELOPE");
    expect(server.submissions[0]!.message).toBeNull();
  });

  it("counts a refused final response as rejected", async () => {
    const server = await startSmtp({ submission: { finalResponse: "550 5.7.1 Message refused" } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("rejected");
    expect(report.response).toBe("550 5.7.1 Message refused");
    expect(report.responseCode).toBe(550);
  });

  it("counts a busy final response as a stated refusal", async () => {
    const server = await startSmtp({ submission: { finalResponse: "421 4.3.2 Try again later" } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("rejected");
    expect(report.responseCode).toBe(421);
  });

  it("counts refused credentials as rejected, before any mail", async () => {
    const server = await startSmtp({ auth: null });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EAUTH");
    expect(server.sawMailSubmission()).toBe(false);
  });

  it("counts a server that advertises no authentication as rejected, before any mail", async () => {
    const server = await startSmtp({ advertiseAuth: false });
    const report = await submitSmtpMessage(request(server.port));

    // `forceAuth` makes the submitter demand the login: without it nodemailer
    // skips the authentication entirely and hands the message to the server
    // unauthenticated (SPEC section 9).
    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("EAUTH");
    expect(server.sawMailSubmission()).toBe(false);
    expect(server.completedSubmissions()).toHaveLength(0);
  });

  it("counts a missing STARTTLS offer as rejected", async () => {
    const server = await startSmtp({ mode: "starttls-missing" });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("rejected");
    expect(report.error?.code).toBe("ETLS");
    expect(server.sawMailSubmission()).toBe(false);
  });

  it("counts a refused greeting as unclassified, before any mail", async () => {
    const server = await startSmtp({ greeting: "421 4.3.2 Too busy, try later" });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("unknown");
    expect(server.sawMailSubmission()).toBe(false);
  });

  it("leaves a lost final response unclassified, with the copy stored", async () => {
    const server = await startSmtp({ submission: { dropAfterData: true } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("unknown");
    // The terminating dot arrived, so the counter holds the stored copy even
    // though the client cannot know it (SPEC F7 step 6).
    const completed = server.completedSubmissions();
    expect(completed).toHaveLength(1);
    expect(Buffer.compare(completed[0]!.message!, RAW)).toBe(0);
  });

  it("leaves a transfer cut off inside the data unclassified and incomplete", async () => {
    const server = await startSmtp({ submission: { dropDuringData: true } });
    const report = await submitSmtpMessage(request(server.port));

    expect(report.state).toBe("unknown");
    expect(server.completedSubmissions()).toHaveLength(0);
    expect(server.submissions[0]!.message).toBeNull();
  });

  it("leaves a stalled final response unclassified after a short timeout", async () => {
    const server = await startSmtp({ submission: { delayFinalResponseMs: 5_000 } });
    const report = await submitSmtpMessage(request(server.port, { ...TIMEOUTS, socketMs: 1_500 }));

    expect(report.state).toBe("unknown");
    expect(Buffer.compare(server.completedSubmissions()[0]!.message!, RAW)).toBe(0);
  }, 10_000);

  it("records commands with the phase they arrived in", async () => {
    const server = await startSmtp({});
    await submitSmtpMessage(request(server.port));

    const authOverTls = server.commands.some(
      (command) => command.phase === "tls" && command.line.startsWith("AUTH"),
    );
    expect(authOverTls).toBe(true);
    expect(server.sawText("MAIL FROM")).toBe(true);
    expect(server.sawText("RCPT TO")).toBe(true);
    expect(server.commands.every((command) => command.line !== "")).toBe(true);
  });

  it("destroys the connection when a line grows past the bound", async () => {
    const server = await startSmtp({});
    const socket = net.createConnection({ host: HOST, port: server.port });
    await new Promise<void>((resolve) => socket.once("connect", resolve));
    // A real client reads the greeting; an unread peer obscures the close.
    socket.on("data", () => undefined);
    socket.on("error", () => undefined);
    const closed = new Promise<void>((resolve) => socket.once("close", resolve));
    // No line terminator: the unterminated remainder is what the bound stops.
    socket.write(`NOOP ${"x".repeat(1_048_577)}`);
    await closed;
    expect(server.commands).toHaveLength(0);
  });
});
